export { default as RedirectPanel } from "./RedirectPanel";
export {default as DriffRegisterPanel} from "./DriffRegisterPanel";
export {default as DriffCreatePanel} from "./DriffCreatePanel";
export {default as LoginPanel} from "./LoginPanel";
export { default as PreLoader } from "./PreLoader";
export { default as ResetPasswordPanel } from "./ResetPasswordPanel";
export { default as UpdatePasswordPanel } from "./UpdatePasswordPanel";
export {default as RegisterPanel} from "./RegisterPanel";
export {default as ExternalRegisterPanel} from "./ExternalRegisterPanel";
export {default as ModalPanel} from "./ModalPanel";
export {default as MagicLinkPanel} from "./MagicLinkPanel";
